In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("house_price_dataset.csv")

In [3]:
df.head()

  house_id  area_sqft  price     condition location
0     H001        NaN    NaN  Needs Repair    Rural
1     H002        NaN    NaN  Needs Repair  Unknown
2     H003        NaN    NaN           NaN    Urban
3     H004        NaN    NaN  Needs Repair    Rural
4     H005        NaN    NaN          Good    Urban

In [4]:
df.shape

(1000, 5)

In [5]:
df.isnull().sum()

house_id       0
area_sqft    654
price        654
condition    381
location     181
dtype: int64

In [6]:
df["area_sqft"] = df["area_sqft"].fillna(df["area_sqft"].mean() , inplace= True)

C:\Users\jiyam\AppData\Local\Temp\ipykernel_14352\2910193756.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["area_sqft"] = df["area_sqft"].fillna(df["area_sqft"].mean() , inplace= True)

In [7]:
df["price"] = df["price"].fillna(df["price"].mean() , inplace= True)

C:\Users\jiyam\AppData\Local\Temp\ipykernel_14352\3944406210.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["price"] = df["price"].fillna(df["price"].mean() , inplace= True)

In [8]:
df.head()

  house_id    area_sqft         price     condition location
0     H001  2757.514451  1.398980e+07  Needs Repair    Rural
1     H002  2757.514451  1.398980e+07  Needs Repair  Unknown
2     H003  2757.514451  1.398980e+07           NaN    Urban
3     H004  2757.514451  1.398980e+07  Needs Repair    Rural
4     H005  2757.514451  1.398980e+07          Good    Urban

In [9]:
x = df[["area_sqft"]]
y = df["price"]

In [10]:
from sklearn.model_selection import train_test_split

In [20]:
x_train , x_test, y_train , y_test = train_test_split(x,y,test_size= 0.25)

In [21]:
x_train

       area_sqft
259  2757.514451
603  2757.514451
784  4606.000000
382  4757.000000
503  2757.514451
..           ...
575  2757.514451
250  2757.514451
213  2757.514451
458  2366.000000
643  2757.514451

[750 rows x 1 columns]

In [22]:
x_test

       area_sqft
562  4808.000000
171  2757.514451
180  2757.514451
541  2757.514451
480  2757.514451
..           ...
211  2757.514451
378  2757.514451
86   4961.000000
261  3876.000000
763  4103.000000

[250 rows x 1 columns]

In [23]:
y_test

562    2.529489e+07
171    1.398980e+07
180    1.398980e+07
541    1.398980e+07
480    1.398980e+07
           ...
211    1.398980e+07
378    1.398980e+07
86     1.977455e+07
261    7.876032e+06
763    2.292756e+07
Name: price, Length: 250, dtype: float64

In [24]:
y_train

259    1.398980e+07
603    1.398980e+07
784    2.992979e+07
382    1.219695e+07
503    1.398980e+07
           ...
575    1.398980e+07
250    1.398980e+07
213    1.398980e+07
458    1.573390e+07
643    1.398980e+07
Name: price, Length: 750, dtype: float64

In [27]:
x_train.shape , y_train.shape

((750, 1), (750,))

In [29]:
x_test.shape , y_test.shape

((250, 1), (250,))